paths:
  /api/adoptions/:
    get:
      summary: To obtain all adoptions
      tags:
      - Adoptions
      responses:
        "200":
          description: "Adoptions succesfully obtained from database"
          content:
            application/json:
              schema:
                type: array 
                items:
                  $ref: '#components/schemas/Adoption'
        "500":
          description: Internal Server Error
  /api/adoptions/{aid}:
    get:
      summary: To obtain an specific adoption by id
      tags:
        - Adoptions
      parameters:
      - name: aid
        in: path
        required: true
        description: adoption id
        schema:
          $type: String
      responses:
        "200":
          description: Adoption succesfully obtained from database by id
          content:
            application/json:
              schema:
                $ref: '#components/schemas/Adoption'
        "400":
          description: Adoption id is required
        "404":
          description: Adoption with id "aid" not found
        "500":
          description: Internal Server Error
  /api/adoptions/user/{uid}/pet/{pid}:
    post:
      summary: To create a new adoption
      tags:
      - Adoptions
      parameters:
      - name: uid
        in: path
        required: true
        description: user id
        schema:
          $type: String
      - name: pid
        in: path
        required: true
        description: pet id
        schema:
          $type: String
      responses:
        "201":
          description: Adoption succesfully created
          content:
            application/json:
              schema:
                $ref: '#components/schemas/Adoption'
        "400":
          description: User or Pet id are required parameters or that pet is already adopted
        "404":
          description: User with id "uid" or Pet with id "pid" not found
        "500":
          description: Internal Server Error
      
components:
  schemas:
    Adoption:
      type: object
      properties:
        _id:
          type: ObjectId
          description: autogenerated mongo id
        owner:
          type: String
          description: pet owner id reference
        pet:
          type: String
          description: pet id reference 
      example:
        _id: ObjectId('68532aee00a6fefe17694ace')
        owner: ObjectId('68532aea00a6refe17894ace')
        pet: ObjectId('68532aee01a6fefet7694bve')
