paths:
  /api/pets/:
    get:
      summary: To obtain all pets
      tags:
      - Pets
      responses:
        "200":
          description: "Pets succesfully obtained from database"
          content:
            application/json:
              schema:
                type: array 
                items:
                  $ref: '#components/schemas/Pet'
        "500":
          description: Internal Server Error
    post:
      summary: To create a new pet
      tags:
       - Pets
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#components/requestBodies/createPet'
      responses:
        "201":
          description: Pet succesfully created
        "400":
          description: Some value in the request body is missing
        "500":
          description: Internal Server Error
  /api/pets/{pid}:
    get:
      summary: To obtain an specific pet by id
      tags:
        - Pets
      parameters:
      - name: pid
        in: path
        required: true
        description: pet id
        schema:
          $type: String
      responses:
        "200":
          description: Pet succesfully obtained from database by id
          content:
            application/json:
              schema:
                $ref: '#components/schemas/Pet'
        "400":
          description: Pet id is required
        "404":
          description: Pet with id "pid" not found
        "500":
          description: Internal Server Error
    put:
      summary: To update an existing pet
      tags:
       - Pets
      parameters:
      - name: pid
        in: path
        required: true
        description: pet id
        schema:
          $type: String
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#components/requestBodies/createPet'
      responses:
        "200":
          description: Pet updated succesfully
        "400":
          description: Pet id is required or some value in the request body is missing or wrong
        "500":
          description: Internal Server Error
    delete:
      summary: To delete an existing pet
      tags:
       - Pets
      parameters:
      - name: pid
        in: path
        required: true
        description: pet id
        schema:
          $type: String
      responses:
        "200":
          description: Pet successfully deleted
        "400":
          description: Pet id is required
        "404":
          description: Pet with id "pid" not found
        "500":
          description: Internal Server Error

components:
  schemas:
    Pet:
      type: object
      properties:
        _id:
          type: ObjectId
          description: autogenerated mongo id
        name:
          type: String
          description: pet name
        specie:
          type: String
          description: pet specie
        birthDate:
          type: String
          description: pet birthDate
        adopted:
          type: String
          description: bolean to indicate if pet is or not adopted
        owner:
          type: ObjectId
          description: owner id
      example:
        _id: ObjectId('68532aee00a6fefe17694ace')
        name: Luna
        specie: Perro Cocker Spaniel
        birthDate: 12-09-2004
        adopted: true
        owner: ObjectId('89542aaa00a4nefe84594acb')
  requestBodies:
    createPet:
      type: object
      properties:
        name:
          type: String
          description: pet name
        specie:
          type: String
          description: pet specie
        birthDate:
          type: String
          description: pet birthDate
      example:
        name: Luna
        specie: Perro Cocker Spaniel
        birthDate: 12-09-2004

        
      